use std::collections::BTreeMap;

use camino::Utf8Path;

use crate::{Error, Result};
use crate::repo::repository::Repository;

/// Database of USE flag descriptions for a Gentoo repository.
///
/// Combines two profile-level files:
/// - `profiles/use.desc` — global flags available to all packages
/// - `profiles/use.local.desc` — package-specific flags (auto-generated by
///   `pmaint` from each package's `metadata.xml`; keyed by `cat/pkg`)
///
/// `use.local.desc` acts as a pre-built index over all `metadata.xml` `<use>`
/// sections, so loading it is O(file size) rather than O(number of packages).
/// For packages not represented (e.g. in overlays that haven't been regen'd),
/// callers can fall back to [`crate::PkgMetadata::load`] directly.
#[derive(Default)]
pub struct UseDb {
    /// Global flag descriptions from `profiles/use.desc`.
    global: BTreeMap<String, String>,
    /// Package-local flag descriptions from `profiles/use.local.desc`.
    /// Key: `cat/pkg` (no version), Value: flag → description.
    local: BTreeMap<String, BTreeMap<String, String>>,
}

impl UseDb {
    /// Load from a repository root directory.
    pub fn load(repo_path: &Utf8Path) -> Result<Self> {
        let profiles = repo_path.join("profiles");
        let global = parse_use_desc(&profiles.join("use.desc"))?;
        let local = parse_use_local_desc(&profiles.join("use.local.desc"))?;
        Ok(Self { global, local })
    }

    /// All global USE flags with their descriptions.
    pub fn global(&self) -> &BTreeMap<String, String> {
        &self.global
    }

    /// Look up a global flag's description.
    pub fn describe_global(&self, flag: &str) -> Option<&str> {
        self.global.get(flag).map(String::as_str)
    }

    /// All packages that declare custom USE flags in `use.local.desc`.
    pub fn packages_with_local_flags(&self) -> impl Iterator<Item = &str> {
        self.local.keys().map(String::as_str)
    }

    /// The local flag map for `cpn` (e.g. `"dev-libs/openssl"`), if any.
    pub fn local_flags(&self, cpn: &str) -> Option<&BTreeMap<String, String>> {
        self.local.get(cpn)
    }

    /// Look up a flag description for `flag` on package `cpn`.
    /// Checks local flags first, then falls back to the global table.
    pub fn describe(&self, cpn: &str, flag: &str) -> Option<&str> {
        self.local
            .get(cpn)
            .and_then(|m| m.get(flag))
            .map(String::as_str)
            .or_else(|| self.describe_global(flag))
    }

    /// Build the local USE flag table by scanning every package's `metadata.xml`.
    ///
    /// Walks the entire repository and collects `<use><flag>` entries from each
    /// package that has a `metadata.xml`.  The global table is left unchanged.
    ///
    /// This is the source-of-truth pass used to regenerate `profiles/use.local.desc`.
    pub fn build_local_from_repo(repo: &Repository) -> Result<Self> {
        let global = parse_use_desc(&repo.path().join("profiles/use.desc"))?;
        let mut local: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();

        for cat in repo.categories() {
            for pkg in cat.packages() {
                if !pkg.has_metadata_xml() {
                    continue;
                }
                let flags = match pkg.metadata_xml()? {
                    Some(meta) if !meta.use_flags().is_empty() => meta.into_use_flags(),
                    _ => continue,
                };
                local.insert(pkg.cpn().to_string(), flags);
            }
        }

        Ok(Self { global, local })
    }

    /// Serialise the local USE flag table to `profiles/use.local.desc` format.
    ///
    /// Entries are sorted by `cat/pkg` then flag name, matching the layout
    /// produced by `pmaint regen`.
    pub fn write_use_local_desc(&self, path: &Utf8Path) -> Result<()> {
        let mut out = String::from(
            "# This file is deprecated as per GLEP 56 in favor of metadata.xml.\n\
             # Please add your descriptions to your package's metadata.xml ONLY.\n\
             # * generated automatically using em maint *\n",
        );

        for (cpn, flags) in &self.local {
            for (flag, desc) in flags {
                out.push_str(&format!("{cpn}:{flag} - {desc}\n"));
            }
        }

        std::fs::write(path, out).map_err(|e| Error::Io {
            path: path.to_path_buf().into_std_path_buf(),
            source: e,
        })
    }
}

/// Parse `profiles/use.desc`.  Each non-comment line is `flag - description`.
fn parse_use_desc(path: &Utf8Path) -> Result<BTreeMap<String, String>> {
    let mut map = BTreeMap::new();
    if !path.exists() {
        return Ok(map);
    }
    let content = std::fs::read_to_string(path).map_err(|e| Error::Io {
        path: path.to_path_buf().into_std_path_buf(),
        source: e,
    })?;
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((flag, desc)) = line.split_once(" - ") {
            map.insert(flag.trim().to_string(), desc.trim().to_string());
        }
    }
    Ok(map)
}

/// Parse `profiles/use.local.desc`.  Each non-comment line is
/// `cat/pkg:flag - description`.
fn parse_use_local_desc(path: &Utf8Path) -> Result<BTreeMap<String, BTreeMap<String, String>>> {
    let mut map: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();
    if !path.exists() {
        return Ok(map);
    }
    let content = std::fs::read_to_string(path).map_err(|e| Error::Io {
        path: path.to_path_buf().into_std_path_buf(),
        source: e,
    })?;
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((pkg_flag, desc)) = line.split_once(" - ") else {
            continue;
        };
        let Some((cpn, flag)) = pkg_flag.split_once(':') else {
            continue;
        };
        map.entry(cpn.trim().to_string())
            .or_default()
            .insert(flag.trim().to_string(), desc.trim().to_string());
    }
    Ok(map)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::tempdir;

    fn write_file(dir: &Utf8Path, name: &str, content: &str) {
        let mut f = std::fs::File::create(dir.join(name)).unwrap();
        f.write_all(content.as_bytes()).unwrap();
    }

    fn make_repo(use_desc: &str, use_local_desc: &str) -> (tempfile::TempDir, UseDb) {
        let dir = tempdir().unwrap();
        let root = Utf8Path::from_path(dir.path()).unwrap();
        let profiles = root.join("profiles");
        std::fs::create_dir(&profiles).unwrap();
        write_file(&profiles, "use.desc", use_desc);
        write_file(&profiles, "use.local.desc", use_local_desc);
        let db = UseDb::load(root).unwrap();
        (dir, db)
    }

    #[test]
    fn global_flags_parsed() {
        let (_dir, db) = make_repo("# comment\nssl - Enable SSL support\ndoc - Build docs\n", "");
        assert_eq!(db.describe_global("ssl"), Some("Enable SSL support"));
        assert_eq!(db.describe_global("doc"), Some("Build docs"));
        assert_eq!(db.describe_global("gtk"), None);
    }

    #[test]
    fn local_flags_parsed() {
        let (_dir, db) = make_repo(
            "",
            "# generated\ndev-libs/openssl:rfc3779 - Enable RFC 3779 support\ndev-libs/openssl:ktls - Enable kernel TLS\n",
        );
        let flags = db.local_flags("dev-libs/openssl").unwrap();
        assert_eq!(flags["rfc3779"], "Enable RFC 3779 support");
        assert_eq!(flags["ktls"], "Enable kernel TLS");
        assert!(db.local_flags("dev-libs/missing").is_none());
    }

    #[test]
    fn describe_local_before_global() {
        let (_dir, db) = make_repo(
            "ssl - Global SSL desc\n",
            "dev-libs/openssl:ssl - Package-specific SSL desc\n",
        );
        assert_eq!(
            db.describe("dev-libs/openssl", "ssl"),
            Some("Package-specific SSL desc")
        );
        assert_eq!(db.describe("dev-libs/other", "ssl"), Some("Global SSL desc"));
    }

    #[test]
    fn packages_with_local_flags() {
        let (_dir, db) = make_repo(
            "",
            "cat/a:flag1 - desc1\ncat/b:flag2 - desc2\ncat/a:flag3 - desc3\n",
        );
        let pkgs: Vec<&str> = db.packages_with_local_flags().collect();
        assert_eq!(pkgs, ["cat/a", "cat/b"]);
        assert_eq!(db.local_flags("cat/a").unwrap().len(), 2);
    }

    #[test]
    fn missing_files_return_empty() {
        let dir = tempdir().unwrap();
        let root = Utf8Path::from_path(dir.path()).unwrap();
        std::fs::create_dir(root.join("profiles")).unwrap();
        let db = UseDb::load(root).unwrap();
        assert_eq!(db.global().len(), 0);
        assert_eq!(db.packages_with_local_flags().count(), 0);
    }
}
