//! `em select pkgconf` — picks the `pkg-config`/`pkgconf` backend and
//! creates the `<CTARGET>-pkg-config` wrapper.
//!
//! Real crossdev ships a generic `cross-pkg-config` script, symlinked per
//! target as `<CTARGET>-pkg-config`, that `toolchain-funcs.eclass`'s
//! `tc-getPKG_CONFIG` searches `$PATH` for. `em` never built an equivalent.
//!
//! A bare symlink to the real backend is not enough: real crossdev's own
//! script (`/usr/bin/cross-pkg-config` on a system with real crossdev
//! installed — GPL-2, `gitweb.gentoo.org/proj/crossdev.git`) does real work
//! beyond forwarding the call —
//! - self-derives `PKG_CONFIG_SYSROOT_DIR` from `$ESYSROOT`/`$SYSROOT`/
//!   `$ROOT` *at invocation time*, so it works standalone too, not only
//!   inside an em-managed build phase where these happen to already be
//!   exported;
//! - probes the ABI-correct `libdir` (`LIBDIR_${ABI}`, falling back to the
//!   compiler's own `-print-file-name=pkgconfig`) instead of hardcoding
//!   `lib64`/`lib`, which matters on multilib-capable targets;
//! - sets `PKG_CONFIG_SYSTEM_LIBRARY_PATH`/`PKG_CONFIG_SYSTEM_INCLUDE_PATH`
//!   and `PKG_CONFIG_FDO_SYSROOT_RULES=1` (pkgconf's sysroot-rewrite rules);
//! - sanitizes `PKG_CONFIG_PATH` (unlike `_LIBDIR`, it *adds* to the search
//!   list, so an inherited host value would leak host `.pc` files in);
//! - sanity-checks the output for `-I`/`-L` flags outside the sysroot and
//!   refuses to emit them — the exact bug class `todo/stage-build-
//!   shakeout.md` documents (`net-libs/libtirpc` leaking via bare
//!   pkg-config into a cross build).
//!
//! [`WRAPPER_TEMPLATE`] below is a close adaptation of that real script
//! (same derivation order, same safety net), with the backend baked in per
//! target/root by `select pkgconf set` instead of resolved dynamically —
//! that's the one piece genuinely specific to *this* wrapper rather than
//! something every invocation should re-derive.
//!
//! No env.d/versioned-profile state otherwise: unlike `compiler`/`binutils`,
//! there's nothing to track beyond which backend the script's own
//! `REAL_PKG_CONFIG=` line names, which `show`/`list` read directly out of
//! the generated file.

use anyhow::{Context, Result};
use camino::{Utf8Path, Utf8PathBuf};

use super::env_d;
use crate::cli::{Cli, PkgconfAction};
use portage_resolve::Roots;

/// The backends this module knows how to wrap, in preference order (used by
/// [`activate_pkgconf`]'s auto-pick and `list`'s ordering).
const BACKENDS: &[&str] = &["pkgconf", "pkg-config"];

/// The `<target>-pkg-config` wrapper script body. `@@BACKEND@@` is the
/// resolved absolute path of the chosen backend; `@@TARGET@@` is the CTARGET
/// (used as the fallback CHOST when the caller hasn't set one, matching
/// real crossdev's own `${0##*/}`-derived default — baked in directly here
/// instead, since a `sh` wrapper can't reliably strip its own argv0 suffix
/// portably the way the Rust generator already knows the target).
///
/// Adapted from real crossdev's `cross-pkg-config` (GPL-2): keeps the
/// EAPI 7+ (`ESYSROOT`), generic (`SYSROOT`), and legacy (`ROOT`) derivation
/// branches plus the ABI/libdir probe, `PKG_CONFIG_PATH` sanitization, and
/// the leaked-host-path safety net; drops the uClinux-dist/manual-install/
/// self-patching branches real crossdev needs to support that don't apply
/// to `em` (this file is regenerated by `em select pkgconf`/toolchain
/// activation, never hand-installed).
const WRAPPER_TEMPLATE: &str = r##"#!/bin/sh
# Autogenerated by `em select pkgconf` -- do not edit, re-run
# `em select pkgconf set <backend> --target @@TARGET@@` instead.
#
# Scopes PKG_CONFIG_SYSROOT_DIR/PKG_CONFIG_LIBDIR/etc. to this target's
# sysroot, self-derived from ROOT/SYSROOT/ESYSROOT at invocation time (works
# standalone, not just inside an em-managed build phase). Adapted from real
# crossdev's own cross-pkg-config wrapper.

REAL_PKG_CONFIG="@@BACKEND@@"

error() { echo "@@TARGET@@-pkg-config: error: $*" 1>&2; exit 1; }
warn() { echo "@@TARGET@@-pkg-config: warning: $*" 1>&2; }

case $1 in
--about|--help|--version)
	exec "${REAL_PKG_CONFIG}" "$@"
	;;
esac

export PKG_CONFIG_LIBDIR=
unset PREFIX

CHOST=${CHOST:-@@TARGET@@}

if [ -n "${ESYSROOT+x}" ]; then
	# Gentoo EAPI 7+
	: "${PKG_CONFIG_SYSROOT_DIR=${SYSROOT}}"
	PREFIX=${ESYSROOT%/}
	PREFIX=${PREFIX#"${SYSROOT%/}"}
elif [ -n "${SYSROOT+x}" ]; then
	# Generic
	: "${PKG_CONFIG_SYSROOT_DIR=${SYSROOT}}"
elif [ -n "${ROOT+x}" ]; then
	# Gentoo EAPI 0-6 / plain ROOT
	: "${PKG_CONFIG_SYSROOT_DIR=${ROOT}}"
else
	# Standalone invocation, nothing set: fall back to the crossdev-shaped
	# /usr/<target> sysroot layout.
	: "${PKG_CONFIG_SYSROOT_DIR=/usr/${CHOST}}"
	[ -d "${PKG_CONFIG_SYSROOT_DIR}" ] || error "need \$ROOT, \$SYSROOT, or \$ESYSROOT set"
fi

export PKG_CONFIG_SYSROOT_DIR="${PKG_CONFIG_SYSROOT_DIR%/}"
PKG_CONFIG_ESYSROOT_DIR=${PKG_CONFIG_SYSROOT_DIR}${PREFIX}

# https://github.com/pkgconf/pkgconf/issues/205
export PKG_CONFIG_FDO_SYSROOT_RULES=1

# PKG_CONFIG_PATH *adds* to the search list (unlike _LIBDIR, which replaces
# it) -- don't trust an inherited value unless it's scoped to this build.
case ${PKG_CONFIG_PATH} in
	"${WORKDIR:-unset}"/*) ;;
	*) unset PKG_CONFIG_PATH ;;
esac

# ABI-correct libdir, matching Gentoo's own get_libdir: prefer an explicit
# LIBDIR_${ABI}, else ask the compiler where it thinks pkgconfig lives.
: "${ABI:=${DEFAULT_ABI:-default}}"
var="LIBDIR_${ABI}"
eval libdir=\${${var}}
if [ -z "${libdir}" ]; then
	libdir=$(realpath "$(${CC:-${CHOST}-gcc} ${CFLAGS} ${LDFLAGS} -print-file-name=pkgconfig)/.." 2>/dev/null)
	libdir=${libdir##*/}
fi
: "${libdir:=lib}"
export \
	PKG_CONFIG_SYSTEM_LIBRARY_PATH="${PKG_CONFIG_ESYSROOT_DIR}/usr/${libdir}:${PKG_CONFIG_ESYSROOT_DIR}/${libdir}" \
	PKG_CONFIG_SYSTEM_INCLUDE_PATH="${PKG_CONFIG_ESYSROOT_DIR}/usr/include"

PKG_CONFIG_LIBDIR="${PKG_CONFIG_ESYSROOT_DIR}/usr/${libdir}/pkgconfig:${PKG_CONFIG_ESYSROOT_DIR}/usr/share/pkgconfig"
export PKG_CONFIG_LIBDIR

output=$("${REAL_PKG_CONFIG}" "$@")
ret=$?

# Refuse to silently leak host -I/-L paths into a cross build (the exact
# bug class todo/stage-build-shakeout.md documents for net-libs/libtirpc).
bad_lines=$(
	printf "%s\n" ${output} |
	grep '^-[LI]' |
	grep -v "^..${PKG_CONFIG_ESYSROOT_DIR}${WORKDIR:+\|^..${WORKDIR}}"
)
if [ -n "${bad_lines}" ]; then
	warn "host -I/-L paths detected outside the sysroot:"
	printf "%s\n" "${bad_lines}" 1>&2
	error "refusing to leak host paths into a cross build: ${output}"
fi
[ -n "${output}" ] && printf "%s\n" "${output}"
exit ${ret}
"##;

/// Find `name` on the real `$PATH`, returning its absolute path if present.
fn find_on_path(name: &str) -> Option<Utf8PathBuf> {
    std::env::var_os("PATH").and_then(|paths| {
        std::env::split_paths(&paths).find_map(|dir| {
            let candidate = dir.join(name);
            candidate
                .is_file()
                .then(|| Utf8PathBuf::from_path_buf(candidate).ok())
                .flatten()
        })
    })
}

/// Path to the `<target>-pkg-config` wrapper, rooted like `select`'s other
/// activation entry points (`env_d::eprefix`).
fn wrapper_path(roots: &Roots, target: &str) -> Utf8PathBuf {
    env_d::eprefix(roots)
        .join("usr/bin")
        .join(format!("{target}-pkg-config"))
}

/// Render [`WRAPPER_TEMPLATE`] for `target`, forwarding to `backend`.
fn render_wrapper(target: &str, backend: &Utf8Path) -> String {
    WRAPPER_TEMPLATE
        .replace("@@TARGET@@", target)
        .replace("@@BACKEND@@", backend.as_str())
}

/// Write the wrapper script at `link`, replacing whatever (if anything) is
/// there, and mark it executable.
fn write_wrapper(link: &Utf8PathBuf, target: &str, backend: &Utf8Path) -> Result<()> {
    if let Some(parent) = link.parent() {
        std::fs::create_dir_all(parent).with_context(|| format!("creating {parent}"))?;
    }
    std::fs::write(link, render_wrapper(target, backend))
        .with_context(|| format!("writing {link}"))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(link, std::fs::Permissions::from_mode(0o755))
            .with_context(|| format!("chmod {link}"))?;
    }
    Ok(())
}

/// The backend a previously-generated wrapper's `REAL_PKG_CONFIG=` line
/// names, plus its resolved path — `None` if there's no wrapper (or it's
/// not one this module generated).
fn current_backend(roots: &Roots, target: &str) -> Option<(String, Utf8PathBuf)> {
    let link = wrapper_path(roots, target);
    let content = std::fs::read_to_string(&link).ok()?;
    let raw = content
        .lines()
        .find_map(|line| line.strip_prefix("REAL_PKG_CONFIG=\"")?.strip_suffix('"'))?;
    let path = Utf8PathBuf::from(raw);
    let name = path.file_name()?.to_string();
    Some((name, path))
}

/// Create/update the `<target>-pkg-config` wrapper if it doesn't already
/// exist, preferring `pkgconf` over `pkg-config` (matching modern Gentoo's
/// own default). Idempotent and non-destructive: a wrapper already present
/// — whether from an earlier auto-activation or a deliberate `em select
/// pkgconf set` — is left untouched, the same `FillGapsOnly`-style
/// deference this codebase uses elsewhere for one-time bootstrap state.
/// Returns `false` if no known backend is reachable at all.
pub fn activate_pkgconf(roots: &Roots, target: &str) -> Result<bool> {
    let link = wrapper_path(roots, target);
    if std::fs::symlink_metadata(&link).is_ok() {
        return Ok(true);
    }
    let Some(backend_path) = BACKENDS.iter().find_map(|b| find_on_path(b)) else {
        return Ok(false);
    };
    write_wrapper(&link, target, &backend_path)?;
    Ok(true)
}

pub fn run(action: &PkgconfAction, globals: &Cli) -> Result<()> {
    let roots = globals.roots();
    let target = match action {
        PkgconfAction::List { target, .. } | PkgconfAction::Show { target, .. } => target
            .clone()
            .unwrap_or_else(|| env_d::get_default_target(globals)),
        PkgconfAction::Set { target, .. } => target
            .clone()
            .unwrap_or_else(|| env_d::get_default_target(globals)),
    };

    match action {
        PkgconfAction::List { .. } => {
            let current = current_backend(&roots, &target);
            for (i, backend) in BACKENDS.iter().enumerate() {
                let reachable = find_on_path(backend);
                let is_current = current.as_ref().is_some_and(|(name, _)| name == backend);
                let mut line = format!("  [{}] {backend}", i + 1);
                if reachable.is_none() {
                    line.push_str(" (not found)");
                }
                if is_current {
                    line.push_str(" *");
                }
                println!("{line}");
            }
            Ok(())
        }
        PkgconfAction::Show { .. } => {
            match current_backend(&roots, &target) {
                Some((name, path)) => println!("{name} ({path})"),
                None => println!("(no pkg-config wrapper set for target '{target}')"),
            }
            Ok(())
        }
        PkgconfAction::Set { backend, .. } => {
            let resolved_name = if let Ok(n) = backend.parse::<usize>() {
                let idx = n.checked_sub(1).context("backend numbers start at 1")?;
                *BACKENDS.get(idx).with_context(|| {
                    format!("backend number {n} out of range (1..={})", BACKENDS.len())
                })?
            } else {
                BACKENDS
                    .iter()
                    .find(|b| **b == backend)
                    .copied()
                    .with_context(|| {
                        format!(
                            "unknown pkg-config backend '{backend}' (expected one of {BACKENDS:?})"
                        )
                    })?
            };
            let backend_path = find_on_path(resolved_name)
                .with_context(|| format!("'{resolved_name}' not found on $PATH"))?;
            let link = wrapper_path(&roots, &target);
            write_wrapper(&link, &target, &backend_path)?;
            println!(">>> {target}-pkg-config -> {backend_path}");
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::Cli;
    use clap::Parser;

    /// `PATH` is process-global and read by every test in this binary
    /// (unlike `HOME`, which `cli.rs`'s tests save/restore without a lock —
    /// `PATH` is used far more pervasively, so a plain save/restore raced
    /// against other `pkgconf` tests running concurrently in the same
    /// process). A process-wide mutex serializes the whole
    /// set-run-restore critical section instead.
    static PATH_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    struct PathGuard {
        saved: Option<std::ffi::OsString>,
        _guard: std::sync::MutexGuard<'static, ()>,
    }

    impl PathGuard {
        fn set(dirs: &[&std::path::Path]) -> Self {
            let guard = PATH_LOCK
                .lock()
                .unwrap_or_else(std::sync::PoisonError::into_inner);
            let saved = std::env::var_os("PATH");
            let joined = std::env::join_paths(dirs).unwrap();
            // SAFETY: serialized by `PATH_LOCK`, held until this guard drops.
            unsafe {
                std::env::set_var("PATH", joined);
            }
            Self {
                saved,
                _guard: guard,
            }
        }
    }

    impl Drop for PathGuard {
        fn drop(&mut self) {
            // SAFETY: see `set`.
            unsafe {
                match &self.saved {
                    Some(p) => std::env::set_var("PATH", p),
                    None => std::env::remove_var("PATH"),
                }
            }
        }
    }

    fn write_fake_backend(dir: &std::path::Path, name: &str) {
        std::fs::write(dir.join(name), "#!/bin/sh\n:\n").unwrap();
    }

    #[test]
    fn activate_pkgconf_creates_wrapper_preferring_pkgconf() {
        let dir = tempfile::tempdir().unwrap();
        let bindir = dir.path().join("bin");
        std::fs::create_dir_all(&bindir).unwrap();
        write_fake_backend(&bindir, "pkgconf");
        write_fake_backend(&bindir, "pkg-config");
        let _path = PathGuard::set(&[&bindir]);

        let root = dir.path().join("root");
        let cli = Cli::parse_from(["em", "--root", root.to_str().unwrap()]);
        let roots = cli.outer_roots().with_own_config_root_if_self_contained();

        let created = activate_pkgconf(&roots, "riscv64-unknown-linux-gnu").unwrap();
        assert!(created);

        let (name, _) = current_backend(&roots, "riscv64-unknown-linux-gnu").unwrap();
        assert_eq!(name, "pkgconf", "must prefer pkgconf over pkg-config");

        let link = wrapper_path(&roots, "riscv64-unknown-linux-gnu");
        let meta = std::fs::metadata(&link).unwrap();
        assert!(
            meta.is_file(),
            "wrapper must be a real script, not a symlink"
        );
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_ne!(
                meta.permissions().mode() & 0o111,
                0,
                "wrapper must be executable"
            );
        }
        let body = std::fs::read_to_string(&link).unwrap();
        assert!(body.contains("PKG_CONFIG_SYSROOT_DIR"));
        assert!(body.contains("PKG_CONFIG_FDO_SYSROOT_RULES"));
    }

    #[test]
    fn activate_pkgconf_falls_back_to_pkg_config_when_pkgconf_missing() {
        let dir = tempfile::tempdir().unwrap();
        let bindir = dir.path().join("bin");
        std::fs::create_dir_all(&bindir).unwrap();
        write_fake_backend(&bindir, "pkg-config");
        let _path = PathGuard::set(&[&bindir]);

        let root = dir.path().join("root");
        let cli = Cli::parse_from(["em", "--root", root.to_str().unwrap()]);
        let roots = cli.outer_roots().with_own_config_root_if_self_contained();

        assert!(activate_pkgconf(&roots, "riscv64-unknown-linux-gnu").unwrap());
        let (name, _) = current_backend(&roots, "riscv64-unknown-linux-gnu").unwrap();
        assert_eq!(name, "pkg-config");
    }

    /// Regression test for the bug this module exists to fix: without any
    /// reachable backend, `activate_pkgconf` must leave no wrapper behind
    /// (not a dangling symlink to a name that doesn't exist).
    #[test]
    fn activate_pkgconf_returns_false_when_no_backend_reachable() {
        let dir = tempfile::tempdir().unwrap();
        let empty_bindir = dir.path().join("empty-bin");
        std::fs::create_dir_all(&empty_bindir).unwrap();
        let _path = PathGuard::set(&[&empty_bindir]);

        let root = dir.path().join("root");
        let cli = Cli::parse_from(["em", "--root", root.to_str().unwrap()]);
        let roots = cli.outer_roots().with_own_config_root_if_self_contained();

        assert!(!activate_pkgconf(&roots, "riscv64-unknown-linux-gnu").unwrap());
        assert!(current_backend(&roots, "riscv64-unknown-linux-gnu").is_none());
    }

    /// A deliberate `em select pkgconf set` choice (or an earlier
    /// auto-activation) must survive a later `activate_pkgconf` call rather
    /// than being silently re-picked.
    #[test]
    fn activate_pkgconf_does_not_clobber_an_existing_wrapper() {
        let dir = tempfile::tempdir().unwrap();
        let bindir = dir.path().join("bin");
        std::fs::create_dir_all(&bindir).unwrap();
        write_fake_backend(&bindir, "pkgconf");
        write_fake_backend(&bindir, "pkg-config");
        let _path = PathGuard::set(&[&bindir]);

        let root = dir.path().join("root");
        let cli = Cli::parse_from(["em", "--root", root.to_str().unwrap()]);
        let roots = cli.outer_roots().with_own_config_root_if_self_contained();

        // Deliberately pick pkg-config first.
        let link = wrapper_path(&roots, "riscv64-unknown-linux-gnu");
        write_wrapper(
            &link,
            "riscv64-unknown-linux-gnu",
            &Utf8PathBuf::from_path_buf(bindir.join("pkg-config")).unwrap(),
        )
        .unwrap();

        assert!(activate_pkgconf(&roots, "riscv64-unknown-linux-gnu").unwrap());
        let (name, _) = current_backend(&roots, "riscv64-unknown-linux-gnu").unwrap();
        assert_eq!(
            name, "pkg-config",
            "existing choice must not be overwritten"
        );
    }

    /// The generated wrapper must actually work as a real shell script,
    /// correctly re-rooting `-I`/`-L` flags for a cross sysroot -- not just
    /// contain plausible-looking text. Runs the real script end-to-end
    /// against a fake pkgconf-like backend (a tiny script printing a fixed
    /// `-I/-L` pair) and a fake sysroot, exercising the ESYSROOT-derivation
    /// branch exactly as an em-managed build phase would set it up.
    #[test]
    fn generated_wrapper_scopes_flags_to_the_sysroot() {
        let dir = tempfile::tempdir().unwrap();
        let sysroot = dir.path().join("sysroot");
        std::fs::create_dir_all(sysroot.join("usr/lib64/pkgconfig")).unwrap();
        std::fs::write(
            sysroot.join("usr/lib64/pkgconfig/fake.pc"),
            "Name: fake\nDescription: fake\nVersion: 1\n",
        )
        .unwrap();

        // A trivial stand-in "real" pkgconf: ignores its args, just prints a
        // sysroot-relative -I/-L pair, matching what a real backend would
        // emit once PKG_CONFIG_SYSROOT_DIR/PKG_CONFIG_LIBDIR are set.
        let backend = dir.path().join("fake-pkgconf");
        std::fs::write(
            &backend,
            "#!/bin/sh\necho \"-I${PKG_CONFIG_SYSROOT_DIR}/usr/include -L${PKG_CONFIG_SYSROOT_DIR}/usr/lib64\"\n",
        )
        .unwrap();
        std::fs::set_permissions(&backend, {
            use std::os::unix::fs::PermissionsExt;
            std::fs::Permissions::from_mode(0o755)
        })
        .unwrap();

        let wrapper = dir.path().join("riscv64-unknown-linux-gnu-pkg-config");
        write_wrapper(
            &Utf8PathBuf::from_path_buf(wrapper.clone()).unwrap(),
            "riscv64-unknown-linux-gnu",
            &Utf8PathBuf::from_path_buf(backend).unwrap(),
        )
        .unwrap();

        let output = std::process::Command::new(&wrapper)
            .arg("fake")
            .arg("--cflags")
            .env("ESYSROOT", &sysroot)
            .env("SYSROOT", &sysroot)
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "wrapper failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(
            stdout.contains(sysroot.to_str().unwrap()),
            "flags must be scoped to the sysroot, got: {stdout}"
        );
    }
}
