//! `em select pkgconf` — picks the `pkg-config`/`pkgconf` backend and
//! creates the `<CTARGET>-pkg-config` wrapper.
//!
//! Real crossdev ships **one** generic `cross-pkg-config` script; every
//! `<CTARGET>-pkg-config` is just a symlink to it, and the script derives
//! its own `CHOST` from `${0##*/}` (its own invoked name) rather than
//! having one baked in per target. `em` mirrors that shape exactly instead
//! of writing a full copy of the script per target: [`SHARED_SCRIPT_NAME`]
//! (`em-cross-pkg-config`) is written once per root, and every configured
//! target's `<CTARGET>-pkg-config` is a plain symlink to it. This isn't
//! just less duplication — it's the more *correct* model, since the
//! backend choice (`pkgconf` vs `pkg-config`) is a host-tool decision that
//! has no reason to vary between cross targets under the same root, and a
//! later fix to the shared script's derivation logic reaches every
//! already-configured target automatically instead of needing each one
//! regenerated by hand.
//!
//! A bare symlink straight to the real backend is *not* enough, though —
//! real crossdev's own script (`/usr/bin/cross-pkg-config` on a system with
//! real crossdev installed — GPL-2, `gitweb.gentoo.org/proj/crossdev.git`)
//! does real work beyond forwarding the call:
//! - self-derives `PKG_CONFIG_SYSROOT_DIR` from `$ESYSROOT`/`$SYSROOT`/
//!   `$ROOT` *at invocation time*, so it works standalone too, not only
//!   inside an em-managed build phase where these happen to already be
//!   exported;
//! - probes the ABI-correct `libdir` (`LIBDIR_${ABI}`, falling back to the
//!   compiler's own `-print-file-name=pkgconfig`) instead of hardcoding
//!   `lib64`/`lib`, which matters on multilib-capable targets;
//! - sets `PKG_CONFIG_SYSTEM_LIBRARY_PATH`/`PKG_CONFIG_SYSTEM_INCLUDE_PATH`
//!   and `PKG_CONFIG_FDO_SYSROOT_RULES=1` (pkgconf's sysroot-rewrite rules);
//! - sanitizes `PKG_CONFIG_PATH` (unlike `_LIBDIR`, it *adds* to the search
//!   list, so an inherited host value would leak host `.pc` files in);
//! - sanity-checks the output for `-I`/`-L` flags outside the sysroot and
//!   refuses to emit them — the exact bug class `todo/stage-build-
//!   shakeout.md` documents (`net-libs/libtirpc` leaking via bare
//!   pkg-config into a cross build).
//!
//! [`SCRIPT_TEMPLATE`] below is a close adaptation of that real script
//! (same derivation order, same safety net); the only piece genuinely
//! specific to *this* installation is which backend `REAL_PKG_CONFIG`
//! forwards to, baked in by `select pkgconf set`/auto-activation.
//!
//! No env.d/versioned-profile state otherwise: unlike `compiler`/
//! `binutils`, there's nothing to track beyond which backend the shared
//! script's own `REAL_PKG_CONFIG=` line names, which `show`/`list` read
//! directly out of the file.

use anyhow::{Context, Result};
use camino::{Utf8Path, Utf8PathBuf};

use super::env_d;
use crate::cli::{Cli, PkgconfAction};
use portage_resolve::Roots;

/// The backends this module knows how to wrap, in preference order (used by
/// [`activate_pkgconf`]'s auto-pick and `list`'s ordering).
const BACKENDS: &[&str] = &["pkgconf", "pkg-config"];

/// Filename of the shared script every `<CTARGET>-pkg-config` symlinks to,
/// mirroring real crossdev's own `cross-pkg-config` — named distinctly
/// (`em-` prefixed) so it's unambiguous this is `em`'s own generated
/// artifact, not a real system crossdev install.
const SHARED_SCRIPT_NAME: &str = "em-cross-pkg-config";

/// The shared script body. `@@BACKEND@@` is the resolved absolute path of
/// the chosen backend — the only thing baked in; `CHOST` is derived from
/// the script's own invoked name (`${0##*/}`, minus the `-pkg-config`
/// suffix), exactly like real crossdev's `cross-pkg-config`, so the same
/// file works correctly through any `<CTARGET>-pkg-config` symlink.
///
/// Adapted from real crossdev's `cross-pkg-config` (GPL-2): keeps the
/// EAPI 7+ (`ESYSROOT`), generic (`SYSROOT`), and legacy (`ROOT`) derivation
/// branches plus the ABI/libdir probe, `PKG_CONFIG_PATH` sanitization, and
/// the leaked-host-path safety net; drops the uClinux-dist/manual-install/
/// self-patching branches real crossdev needs to support that don't apply
/// to `em` (this file is regenerated by `em select pkgconf`/toolchain
/// activation, never hand-installed).
const SCRIPT_TEMPLATE: &str = r##"#!/bin/sh
# Autogenerated by `em select pkgconf` -- do not edit, re-run
# `em select pkgconf set <backend>` instead (affects every <CTARGET>-
# pkg-config symlink under this root, not just one target).
#
# Scopes PKG_CONFIG_SYSROOT_DIR/PKG_CONFIG_LIBDIR/etc. to this target's
# sysroot, self-derived from ROOT/SYSROOT/ESYSROOT at invocation time (works
# standalone, not just inside an em-managed build phase). Adapted from real
# crossdev's own cross-pkg-config wrapper. One copy of this script is
# shared by every <CTARGET>-pkg-config symlink; CHOST comes from $0.

REAL_PKG_CONFIG="@@BACKEND@@"

error() { echo "${0##*/}: error: $*" 1>&2; exit 1; }
warn() { echo "${0##*/}: warning: $*" 1>&2; }

case $1 in
--about|--help|--version)
	exec "${REAL_PKG_CONFIG}" "$@"
	;;
esac

export PKG_CONFIG_LIBDIR=
unset PREFIX

if [ -z "${CHOST}" ] ; then
	CHOST=${0##*/}
	CHOST=${CHOST%-pkg-config}
fi

if [ -n "${ESYSROOT+x}" ]; then
	# Gentoo EAPI 7+
	: "${PKG_CONFIG_SYSROOT_DIR=${SYSROOT}}"
	PREFIX=${ESYSROOT%/}
	PREFIX=${PREFIX#"${SYSROOT%/}"}
elif [ -n "${SYSROOT+x}" ]; then
	# Generic
	: "${PKG_CONFIG_SYSROOT_DIR=${SYSROOT}}"
elif [ -n "${ROOT+x}" ]; then
	# Gentoo EAPI 0-6 / plain ROOT
	: "${PKG_CONFIG_SYSROOT_DIR=${ROOT}}"
else
	# Standalone invocation, nothing set: fall back to the crossdev-shaped
	# /usr/<target> sysroot layout.
	: "${PKG_CONFIG_SYSROOT_DIR=/usr/${CHOST}}"
	[ -d "${PKG_CONFIG_SYSROOT_DIR}" ] || error "need \$ROOT, \$SYSROOT, or \$ESYSROOT set"
fi

export PKG_CONFIG_SYSROOT_DIR="${PKG_CONFIG_SYSROOT_DIR%/}"
PKG_CONFIG_ESYSROOT_DIR=${PKG_CONFIG_SYSROOT_DIR}${PREFIX}

# https://github.com/pkgconf/pkgconf/issues/205
export PKG_CONFIG_FDO_SYSROOT_RULES=1

# PKG_CONFIG_PATH *adds* to the search list (unlike _LIBDIR, which replaces
# it) -- don't trust an inherited value unless it's scoped to this build.
case ${PKG_CONFIG_PATH} in
	"${WORKDIR:-unset}"/*) ;;
	*) unset PKG_CONFIG_PATH ;;
esac

# ABI-correct libdir, matching Gentoo's own get_libdir: prefer an explicit
# LIBDIR_${ABI}, else ask the compiler where it thinks pkgconfig lives.
: "${ABI:=${DEFAULT_ABI:-default}}"
var="LIBDIR_${ABI}"
eval libdir=\${${var}}
if [ -z "${libdir}" ]; then
	libdir=$(realpath "$(${CC:-${CHOST}-gcc} ${CFLAGS} ${LDFLAGS} -print-file-name=pkgconfig)/.." 2>/dev/null)
	libdir=${libdir##*/}
fi
: "${libdir:=lib}"
export \
	PKG_CONFIG_SYSTEM_LIBRARY_PATH="${PKG_CONFIG_ESYSROOT_DIR}/usr/${libdir}:${PKG_CONFIG_ESYSROOT_DIR}/${libdir}" \
	PKG_CONFIG_SYSTEM_INCLUDE_PATH="${PKG_CONFIG_ESYSROOT_DIR}/usr/include"

PKG_CONFIG_LIBDIR="${PKG_CONFIG_ESYSROOT_DIR}/usr/${libdir}/pkgconfig:${PKG_CONFIG_ESYSROOT_DIR}/usr/share/pkgconfig"
export PKG_CONFIG_LIBDIR

output=$("${REAL_PKG_CONFIG}" "$@")
ret=$?

# Refuse to silently leak host -I/-L paths into a cross build (the exact
# bug class todo/stage-build-shakeout.md documents for net-libs/libtirpc).
bad_lines=$(
	printf "%s\n" ${output} |
	grep '^-[LI]' |
	grep -v "^..${PKG_CONFIG_ESYSROOT_DIR}${WORKDIR:+\|^..${WORKDIR}}"
)
if [ -n "${bad_lines}" ]; then
	warn "host -I/-L paths detected outside the sysroot:"
	printf "%s\n" "${bad_lines}" 1>&2
	error "refusing to leak host paths into a cross build: ${output}"
fi
[ -n "${output}" ] && printf "%s\n" "${output}"
exit ${ret}
"##;

/// Find `name` on the real `$PATH`, returning its absolute path if present.
fn find_on_path(name: &str) -> Option<Utf8PathBuf> {
    std::env::var_os("PATH").and_then(|paths| {
        std::env::split_paths(&paths).find_map(|dir| {
            let candidate = dir.join(name);
            candidate
                .is_file()
                .then(|| Utf8PathBuf::from_path_buf(candidate).ok())
                .flatten()
        })
    })
}

/// Path to the root's one shared script, rooted like `select`'s other
/// activation entry points (`env_d::eprefix`).
fn shared_script_path(roots: &Roots) -> Utf8PathBuf {
    env_d::eprefix(roots)
        .join("usr/bin")
        .join(SHARED_SCRIPT_NAME)
}

/// Path to the `<target>-pkg-config` symlink.
fn wrapper_path(roots: &Roots, target: &str) -> Utf8PathBuf {
    env_d::eprefix(roots)
        .join("usr/bin")
        .join(format!("{target}-pkg-config"))
}

/// Write/overwrite the shared script, forwarding to `backend`, and mark it
/// executable.
fn write_shared_script(roots: &Roots, backend: &Utf8Path) -> Result<Utf8PathBuf> {
    let path = shared_script_path(roots);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).with_context(|| format!("creating {parent}"))?;
    }
    let body = SCRIPT_TEMPLATE.replace("@@BACKEND@@", backend.as_str());
    std::fs::write(&path, body).with_context(|| format!("writing {path}"))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))
            .with_context(|| format!("chmod {path}"))?;
    }
    Ok(path)
}

/// Symlink `<target>-pkg-config` to the shared script (bare relative
/// filename, matching `compiler.rs`'s own same-directory wrapper links).
fn link_target(roots: &Roots, target: &str) -> Result<()> {
    let link = wrapper_path(roots, target);
    env_d::symlink_force(Utf8Path::new(SHARED_SCRIPT_NAME), &link)
}

/// The backend the shared script's `REAL_PKG_CONFIG=` line currently names,
/// plus its resolved path — `None` if there's no shared script yet.
fn current_backend(roots: &Roots) -> Option<(String, Utf8PathBuf)> {
    let content = std::fs::read_to_string(shared_script_path(roots)).ok()?;
    let raw = content
        .lines()
        .find_map(|line| line.strip_prefix("REAL_PKG_CONFIG=\"")?.strip_suffix('"'))?;
    let path = Utf8PathBuf::from(raw);
    let name = path.file_name()?.to_string();
    Some((name, path))
}

/// Create the `<target>-pkg-config` symlink (and the shared script it
/// points to, if this is the first target activated under this root) if
/// the symlink doesn't already exist, preferring `pkgconf` over
/// `pkg-config` (matching modern Gentoo's own default). Idempotent and
/// non-destructive: an existing symlink — from an earlier auto-activation
/// or a deliberate `em select pkgconf set` — is left untouched, and an
/// already-existing shared script's backend choice is never silently
/// re-picked, the same `FillGapsOnly`-style deference this codebase uses
/// elsewhere for one-time bootstrap state. Returns `false` if no known
/// backend is reachable and there's no shared script to link to yet.
pub fn activate_pkgconf(roots: &Roots, target: &str) -> Result<bool> {
    let link = wrapper_path(roots, target);
    if std::fs::symlink_metadata(&link).is_ok() {
        return Ok(true);
    }
    if current_backend(roots).is_none() {
        let Some(backend_path) = BACKENDS.iter().find_map(|b| find_on_path(b)) else {
            return Ok(false);
        };
        write_shared_script(roots, &backend_path)?;
    }
    link_target(roots, target)?;
    Ok(true)
}

pub fn run(action: &PkgconfAction, globals: &Cli) -> Result<()> {
    let roots = globals.roots();
    let target = match action {
        PkgconfAction::List { target, .. } | PkgconfAction::Show { target, .. } => target
            .clone()
            .unwrap_or_else(|| env_d::get_default_target(globals)),
        PkgconfAction::Set { target, .. } => target
            .clone()
            .unwrap_or_else(|| env_d::get_default_target(globals)),
    };

    match action {
        PkgconfAction::List { .. } => {
            let current = current_backend(&roots);
            for (i, backend) in BACKENDS.iter().enumerate() {
                let reachable = find_on_path(backend);
                let is_current = current.as_ref().is_some_and(|(name, _)| name == backend);
                let mut line = format!("  [{}] {backend}", i + 1);
                if reachable.is_none() {
                    line.push_str(" (not found)");
                }
                if is_current {
                    line.push_str(" *");
                }
                println!("{line}");
            }
            Ok(())
        }
        PkgconfAction::Show { .. } => {
            match current_backend(&roots) {
                Some((name, path)) => println!("{name} ({path})"),
                None => println!("(no pkg-config backend set for this root)"),
            }
            Ok(())
        }
        PkgconfAction::Set { backend, .. } => {
            let resolved_name = if let Ok(n) = backend.parse::<usize>() {
                let idx = n.checked_sub(1).context("backend numbers start at 1")?;
                *BACKENDS.get(idx).with_context(|| {
                    format!("backend number {n} out of range (1..={})", BACKENDS.len())
                })?
            } else {
                BACKENDS
                    .iter()
                    .find(|b| **b == backend)
                    .copied()
                    .with_context(|| {
                        format!(
                            "unknown pkg-config backend '{backend}' (expected one of {BACKENDS:?})"
                        )
                    })?
            };
            let backend_path = find_on_path(resolved_name)
                .with_context(|| format!("'{resolved_name}' not found on $PATH"))?;
            // A `set` is a deliberate, explicit choice: unlike auto-activation,
            // this always (re)writes the shared script -- affecting every
            // target's symlink under this root, not just the one named here.
            write_shared_script(&roots, &backend_path)?;
            link_target(&roots, &target)?;
            println!(
                ">>> pkg-config backend set to {backend_path} ({target}-pkg-config and any other configured target)"
            );
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::Cli;
    use clap::Parser;

    /// `PATH` is process-global and read by every test in this binary
    /// (unlike `HOME`, which `cli.rs`'s tests save/restore without a lock —
    /// `PATH` is used far more pervasively, so a plain save/restore raced
    /// against other `pkgconf` tests running concurrently in the same
    /// process). A process-wide mutex serializes the whole
    /// set-run-restore critical section instead.
    static PATH_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    struct PathGuard {
        saved: Option<std::ffi::OsString>,
        _guard: std::sync::MutexGuard<'static, ()>,
    }

    impl PathGuard {
        fn set(dirs: &[&std::path::Path]) -> Self {
            let guard = PATH_LOCK
                .lock()
                .unwrap_or_else(std::sync::PoisonError::into_inner);
            let saved = std::env::var_os("PATH");
            let joined = std::env::join_paths(dirs).unwrap();
            // SAFETY: serialized by `PATH_LOCK`, held until this guard drops.
            unsafe {
                std::env::set_var("PATH", joined);
            }
            Self {
                saved,
                _guard: guard,
            }
        }
    }

    impl Drop for PathGuard {
        fn drop(&mut self) {
            // SAFETY: see `set`.
            unsafe {
                match &self.saved {
                    Some(p) => std::env::set_var("PATH", p),
                    None => std::env::remove_var("PATH"),
                }
            }
        }
    }

    fn write_fake_backend(dir: &std::path::Path, name: &str) {
        std::fs::write(dir.join(name), "#!/bin/sh\n:\n").unwrap();
    }

    fn test_roots(dir: &std::path::Path) -> Roots {
        let root = dir.join("root");
        let cli = Cli::parse_from(["em", "--root", root.to_str().unwrap()]);
        cli.outer_roots().with_own_config_root_if_self_contained()
    }

    #[test]
    fn activate_pkgconf_creates_shared_script_preferring_pkgconf() {
        let dir = tempfile::tempdir().unwrap();
        let bindir = dir.path().join("bin");
        std::fs::create_dir_all(&bindir).unwrap();
        write_fake_backend(&bindir, "pkgconf");
        write_fake_backend(&bindir, "pkg-config");
        let _path = PathGuard::set(&[&bindir]);

        let roots = test_roots(dir.path());
        assert!(activate_pkgconf(&roots, "riscv64-unknown-linux-gnu").unwrap());

        let (name, _) = current_backend(&roots).unwrap();
        assert_eq!(name, "pkgconf", "must prefer pkgconf over pkg-config");

        let script = shared_script_path(&roots);
        let meta = std::fs::metadata(&script).unwrap();
        assert!(meta.is_file(), "shared script must be a real file");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_ne!(
                meta.permissions().mode() & 0o111,
                0,
                "shared script must be executable"
            );
        }
        let body = std::fs::read_to_string(&script).unwrap();
        assert!(body.contains("PKG_CONFIG_SYSROOT_DIR"));
        assert!(body.contains("PKG_CONFIG_FDO_SYSROOT_RULES"));

        let link = wrapper_path(&roots, "riscv64-unknown-linux-gnu");
        assert_eq!(
            std::fs::read_link(&link).unwrap(),
            std::path::Path::new(SHARED_SCRIPT_NAME),
            "<target>-pkg-config must be a symlink to the shared script"
        );
    }

    #[test]
    fn activate_pkgconf_falls_back_to_pkg_config_when_pkgconf_missing() {
        let dir = tempfile::tempdir().unwrap();
        let bindir = dir.path().join("bin");
        std::fs::create_dir_all(&bindir).unwrap();
        write_fake_backend(&bindir, "pkg-config");
        let _path = PathGuard::set(&[&bindir]);

        let roots = test_roots(dir.path());
        assert!(activate_pkgconf(&roots, "riscv64-unknown-linux-gnu").unwrap());
        let (name, _) = current_backend(&roots).unwrap();
        assert_eq!(name, "pkg-config");
    }

    /// Regression test for the bug this module exists to fix: without any
    /// reachable backend, `activate_pkgconf` must leave no shared script or
    /// symlink behind (not one pointing at a name that doesn't exist).
    #[test]
    fn activate_pkgconf_returns_false_when_no_backend_reachable() {
        let dir = tempfile::tempdir().unwrap();
        let empty_bindir = dir.path().join("empty-bin");
        std::fs::create_dir_all(&empty_bindir).unwrap();
        let _path = PathGuard::set(&[&empty_bindir]);

        let roots = test_roots(dir.path());
        assert!(!activate_pkgconf(&roots, "riscv64-unknown-linux-gnu").unwrap());
        assert!(current_backend(&roots).is_none());
    }

    /// A deliberate `em select pkgconf set` choice (or an earlier
    /// auto-activation) must survive a later `activate_pkgconf` call rather
    /// than being silently re-picked -- for a *second* target under the
    /// same root too, not just the one that first created the script.
    #[test]
    fn activate_pkgconf_shares_one_choice_across_multiple_targets() {
        let dir = tempfile::tempdir().unwrap();
        let bindir = dir.path().join("bin");
        std::fs::create_dir_all(&bindir).unwrap();
        write_fake_backend(&bindir, "pkgconf");
        write_fake_backend(&bindir, "pkg-config");
        let _path = PathGuard::set(&[&bindir]);

        let roots = test_roots(dir.path());

        // Deliberately pick pkg-config first, for one target.
        run(
            &PkgconfAction::Set {
                backend: "pkg-config".to_string(),
                target: Some("riscv64-unknown-linux-gnu".to_string()),
            },
            &Cli::parse_from([
                "em",
                "--root",
                dir.path().join("root").to_str().unwrap(),
                "--config-root",
                dir.path().join("root").to_str().unwrap(),
            ]),
        )
        .unwrap();

        // A second target's auto-activation must reuse the same choice,
        // not silently re-pick pkgconf.
        assert!(activate_pkgconf(&roots, "aarch64-unknown-linux-gnu").unwrap());
        let (name, _) = current_backend(&roots).unwrap();
        assert_eq!(
            name, "pkg-config",
            "existing root-wide choice must not be overwritten by a second target"
        );

        // Both targets' symlinks point at the one shared script.
        for target in ["riscv64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"] {
            let link = wrapper_path(&roots, target);
            assert_eq!(
                std::fs::read_link(&link).unwrap(),
                std::path::Path::new(SHARED_SCRIPT_NAME)
            );
        }
    }

    /// The shared script must actually work as a real shell script,
    /// correctly re-rooting `-I`/`-L` flags for a cross sysroot -- not just
    /// contain plausible-looking text. Runs it through a per-target symlink
    /// (exercising the `${0##*/}`-derived CHOST, exactly like real
    /// crossdev) against a fake pkgconf-like backend and a fake sysroot.
    #[test]
    fn generated_wrapper_scopes_flags_to_the_sysroot() {
        let dir = tempfile::tempdir().unwrap();
        let sysroot = dir.path().join("sysroot");
        std::fs::create_dir_all(sysroot.join("usr/lib64/pkgconfig")).unwrap();
        std::fs::write(
            sysroot.join("usr/lib64/pkgconfig/fake.pc"),
            "Name: fake\nDescription: fake\nVersion: 1\n",
        )
        .unwrap();

        // A trivial stand-in "real" pkgconf: ignores its args, just prints a
        // sysroot-relative -I/-L pair, matching what a real backend would
        // emit once PKG_CONFIG_SYSROOT_DIR/PKG_CONFIG_LIBDIR are set.
        let backend = dir.path().join("fake-pkgconf");
        std::fs::write(
            &backend,
            "#!/bin/sh\necho \"-I${PKG_CONFIG_SYSROOT_DIR}/usr/include -L${PKG_CONFIG_SYSROOT_DIR}/usr/lib64\"\n",
        )
        .unwrap();
        std::fs::set_permissions(&backend, {
            use std::os::unix::fs::PermissionsExt;
            std::fs::Permissions::from_mode(0o755)
        })
        .unwrap();

        let bindir = dir.path().join("usr-bin");
        std::fs::create_dir_all(&bindir).unwrap();
        let script = bindir.join(SHARED_SCRIPT_NAME);
        std::fs::write(
            &script,
            SCRIPT_TEMPLATE.replace("@@BACKEND@@", backend.to_str().unwrap()),
        )
        .unwrap();
        std::fs::set_permissions(&script, {
            use std::os::unix::fs::PermissionsExt;
            std::fs::Permissions::from_mode(0o755)
        })
        .unwrap();
        let wrapper = bindir.join("riscv64-unknown-linux-gnu-pkg-config");
        std::os::unix::fs::symlink(SHARED_SCRIPT_NAME, &wrapper).unwrap();

        let output = std::process::Command::new(&wrapper)
            .arg("fake")
            .arg("--cflags")
            .env("ESYSROOT", &sysroot)
            .env("SYSROOT", &sysroot)
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "wrapper failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(
            stdout.contains(sysroot.to_str().unwrap()),
            "flags must be scoped to the sysroot, got: {stdout}"
        );
    }
}
