//! `env-update`: regenerate `${ROOT}/etc/profile.env` and the dynamic
//! linker configuration from `${ROOT}/etc/env.d/`.
//!
//! Mirrors portage's behaviour: env.d files are read in sorted order;
//! PATH-like variables accumulate colon-separated (later files append),
//! CONFIG_PROTECT-like accumulate space-separated, anything else is
//! last-file-wins. `LDPATH` additionally feeds `etc/ld.so.conf`, and
//! `ldconfig` is invoked to rebuild the cache (best-effort when
//! unprivileged).

use std::collections::BTreeMap;

use anyhow::{Context, Result};
use camino::Utf8Path;

/// Variables joined with `:` across env.d files (portage's COLON_SEPARATED).
const COLON_SEPARATED: &[&str] = &[
    "ADA_INCLUDE_PATH",
    "ADA_OBJECTS_PATH",
    "CLASSPATH",
    "INFODIR",
    "INFOPATH",
    "KDEDIRS",
    "LDPATH",
    "MANPATH",
    "PATH",
    "PKG_CONFIG_PATH",
    "PRELINK_PATH",
    "PRELINK_PATH_MASK",
    "PYTHONPATH",
    "ROOTPATH",
];

/// Variables joined with a space (portage's SPACE_SEPARATED).
const SPACE_SEPARATED: &[&str] = &["CONFIG_PROTECT", "CONFIG_PROTECT_MASK"];

/// Regenerate `etc/profile.env` and `etc/ld.so.conf` under `root`, then
/// refresh the `ld.so` cache.
pub fn env_update(root: &Utf8Path) -> Result<()> {
    let env_d = root.join("etc/env.d");
    let mut merged: BTreeMap<String, String> = BTreeMap::new();

    let mut entries: Vec<_> = match std::fs::read_dir(env_d.as_std_path()) {
        Ok(rd) => rd
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| {
                p.is_file()
                    && p.file_name()
                        .and_then(|n| n.to_str())
                        .is_some_and(|n| !n.starts_with('.') && !n.ends_with('~'))
            })
            .collect(),
        // No env.d at all (fresh prefix): nothing to merge, still write an
        // empty profile.env so consumers can source it.
        Err(_) => Vec::new(),
    };
    entries.sort();

    for path in &entries {
        let Ok(content) = std::fs::read_to_string(path) else {
            continue;
        };
        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let Some((key, raw)) = line.split_once('=') else {
                continue;
            };
            let key = key.trim_start_matches("export ").trim();
            let value = raw.trim().trim_matches('"').trim_matches('\'');
            if key.is_empty() || value.is_empty() {
                continue;
            }
            if COLON_SEPARATED.contains(&key) {
                let entry = merged.entry(key.to_string()).or_default();
                if !entry.is_empty() {
                    entry.push(':');
                }
                entry.push_str(value);
            } else if SPACE_SEPARATED.contains(&key) {
                let entry = merged.entry(key.to_string()).or_default();
                if !entry.is_empty() {
                    entry.push(' ');
                }
                entry.push_str(value);
            } else {
                merged.insert(key.to_string(), value.to_string());
            }
        }
    }

    // etc/profile.env
    let mut profile_env = String::from(
        "# Autogenerated by em env-update; do not edit (see /etc/env.d).\n",
    );
    for (key, value) in &merged {
        // LDPATH feeds ld.so.conf, not the shell environment (portage skips it).
        if key == "LDPATH" {
            continue;
        }
        profile_env.push_str(&format!("export {key}='{value}'\n"));
    }
    let etc = root.join("etc");
    std::fs::create_dir_all(etc.as_std_path()).context("creating etc")?;
    std::fs::write(etc.join("profile.env").as_std_path(), profile_env)
        .context("writing profile.env")?;

    // etc/ld.so.conf from LDPATH.
    if let Some(ldpath) = merged.get("LDPATH") {
        let mut conf =
            String::from("# Autogenerated by em env-update; do not edit (see /etc/env.d).\n");
        for dir in ldpath.split(':').filter(|d| !d.is_empty()) {
            conf.push_str(dir);
            conf.push('\n');
        }
        std::fs::write(etc.join("ld.so.conf").as_std_path(), conf)
            .context("writing ld.so.conf")?;

        // Refresh the cache; best-effort (needs write access, and ldconfig
        // may be absent on non-glibc roots).
        let status = if root == "/" {
            std::process::Command::new("ldconfig").status()
        } else {
            std::process::Command::new("ldconfig")
                .arg("-r")
                .arg(root.as_std_path())
                .status()
        };
        match status {
            Ok(s) if s.success() => {}
            Ok(s) => eprintln!("env-update: ldconfig exited with {s}"),
            Err(e) => eprintln!("env-update: ldconfig not run: {e}"),
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn merges_env_d_with_portage_semantics() {
        let dir = tempfile::tempdir().unwrap();
        let root = Utf8Path::from_path(dir.path()).unwrap();
        let env_d = root.join("etc/env.d");
        std::fs::create_dir_all(&env_d).unwrap();
        std::fs::write(env_d.join("00basic"), "PATH=\"/usr/bin\"\nEDITOR=nano\n").unwrap();
        std::fs::write(
            env_d.join("50extra"),
            "PATH=\"/opt/bin\"\nEDITOR=vim\nCONFIG_PROTECT=\"/etc/extra\"\nLDPATH=\"/usr/lib64/extra\"\n",
        )
        .unwrap();

        env_update(root).unwrap();

        let profile = std::fs::read_to_string(root.join("etc/profile.env")).unwrap();
        assert!(profile.contains("export PATH='/usr/bin:/opt/bin'"), "{profile}");
        assert!(profile.contains("export EDITOR='vim'"), "last wins: {profile}");
        assert!(profile.contains("export CONFIG_PROTECT='/etc/extra'"));
        assert!(!profile.contains("LDPATH"), "LDPATH is linker-only");

        let ld = std::fs::read_to_string(root.join("etc/ld.so.conf")).unwrap();
        assert!(ld.contains("/usr/lib64/extra"));
    }
}
